CRUDPython/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudapp.urls')),
]

crudapp/urls.py
from django.contrib import admin
from django.urls import path
from crudapp import views

urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

crudapp/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    firstname = models.CharField(max_length=30)  
    lastname = models.CharField(max_length=30)
    email = models.EmailField(max_length=45)  
    contact = models.CharField(max_length=15)
    password = models.CharField(max_length=20)
    address = models.CharField(max_length=200)  
    class Meta:  
        db_table = "employee"

crudapp/forms.py
from django import forms
from crudapp.models import Employee

class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee
        fields = "__all__"

crudapp/views.py
# Create your views here.
from django.shortcuts import render, redirect
from crudapp.forms import EmployeeForm
from crudapp.models import Employee


def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})  
def show(request):
    employees = Employee.objects.all()  
    return render(request, "show.html", {'employees':employees})
def edit(request, id):
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  
def update(request, id):
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  
def destroy(request, id):
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")

crudapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Id:</label>
                <div class="col-sm-4">
                    <input class="form-control" type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee First Name:</label>
                <div class="col-sm-4">
                    <input class="form-control" type="text" name="firstname" id="id_firstname" required maxlength="100"
                        value="{{ employee.firstname }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Last Name:</label>
                <div class="col-sm-4">
                    <input class="form-control" type="text" name="lastname" id="id_lastname" required maxlength="100"
                        value="{{ employee.lastname }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    <input class="form-control" type="email" name="email" id="id_email" required maxlength="254"
                        value="{{ employee.email }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    <input  class="form-control" type="password" name="password" id="id_password" required maxlength="254"
                        value="{{ employee.password }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    <input class="form-control" type="text" name="contact" id="id_contact" required maxlength="15"
                        value="{{ employee.contact }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    <textarea class="form-control" type="text" name="address" id="id_address" required maxlength="15"
                        value="{{ employee.address }}" >{{ employee.address }}</textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Update</button>
                    <a href="/show" class="btn btn-info">Back To List</a>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

crudapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
    <form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Id:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="eid" required title="Employee Id is required" >
                    <!-- {{ form.eid }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee First Name:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="firstname" >
                    <!-- {{ form.firstname }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Last Name:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="lastname" >
                    <!-- {{ form.lastname }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="email" >
                    <!-- {{ form.email }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Password:</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" name="password" >
                    <!-- {{ form.password }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    <input type="text"  name="contact" class="form-control" />
                    <!-- {{ form.contact }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Address:</label>
                <div class="col-sm-4">
                    <textarea name="address" id="" rows="3" class="form-control"></textarea>
                    <!-- {{ form.address }} -->
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="/show" class="btn btn-info">Back To List</a>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

crudapp/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
    <table class="table table-striped table-bordered table-sm">
        <thead class="thead-dark">
            <tr>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Employee Email</th>
                <th>Password</th>
                <th>Employee Contact</th>
                <th>Address</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.eid }}</td>
                <td>{{ employee.firstname  }} {{ employee.lastname  }}</td>
                <td>{{ employee.email }}</td>
                <td>{{ employee.password }}</td>
                <td>{{ employee.contact }}</td>
                <td>{{ employee.address }}</td>
                <td>
                    <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                    <a href="/delete/{{ employee.id }}" onclick="return confirm('Are you sure to remove this record?')" >Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <br>
    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>

</html>